name: linux-ksmbd-oot CI

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Download the kernel
      run: |
        sudo apt-get update
        sudo apt-get install libelf-dev wget tar gzip python3 git clang libdw-dev libdwarf-dev
        git clone --depth 1 -b azure-fde-6.17 https://git.launchpad.net/~canonical-kernel/ubuntu/+source/linux-azure/+git/noble linux-azure

    - name: Prerequisite for xfstests & smbtorture testing
      run: |
        sudo apt-get install cifs-utils
        sudo apt-get install linux-headers-$(uname -r)
        sudo apt-get install autoconf libtool pkg-config libnl-3-dev libnl-genl-3-dev libglib2.0-dev
        sudo apt-get install xfslibs-dev uuid-dev libtool-bin xfsprogs libgdbm-dev gawk fio attr libattr1-dev libacl1-dev libaio-dev
        sudo apt-get install liblmdb-dev libgnutls28-dev libgpgme-dev libjansson-dev libarchive-dev libacl1-dev
        sudo apt-get install gnutls-bin libparse-yapp-perl libjansson-dev libarchive-dev libjson-perl
        sudo apt-get install libgettextpo-dev libinih-dev liburcu-dev libdevmapper-dev libicu-dev

        git clone -b v1-sanitizer-on-master https://github.com/yskzalloc/ksmbd-tools.git
        git clone https://github.com/namjaejeon/cifsd-test-result
        git clone --depth 1 https://github.com/samba-team/samba.git
        git clone --depth 1 git://git.kernel.org/pub/scm/fs/xfs/xfsprogs-dev.git

        export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        export PATH=/usr/local/lib:$PATH
        sudo useradd fsgqa
        sudo useradd 123456-fsgqa

    - name: Compile and load CIFS & KSMBD module
      working-directory: linux-azure
      run: |
        uname -r
        git --no-pager log -1 --oneline

        make localmodconfig > /dev/null

        ./scripts/config --module CONFIG_CIFS
        ./scripts/config --enable CONFIG_CIFS_STATS2
        ./scripts/config --enable CONFIG_CIFS_ALLOW_INSECURE_LEGACY
        ./scripts/config --enable CONFIG_CIFS_UPCALL
        ./scripts/config --enable CONFIG_CIFS_XATTR
        ./scripts/config --enable CONFIG_CIFS_POSIX
        ./scripts/config --enable CONFIG_CIFS_DEBUG
        ./scripts/config --enable CONFIG_CIFS_DEBUG2
        ./scripts/config --enable CONFIG_CIFS_DEBUG_DUMP_KEYS
        ./scripts/config --enable CONFIG_CIFS_DFS_UPCALL
        ./scripts/config --enable CONFIG_CIFS_SWN_UPCALL
        ./scripts/config --enable CONFIG_CIFS_SMB_DIRECT
        ./scripts/config --enable CONFIG_CIFS_FSCACHE
        ./scripts/config --enable CONFIG_CIFS_ROOT
        ./scripts/config --enable CONFIG_CIFS_COMPRESSION

        ./scripts/config --module CONFIG_SMB_SERVER
        ./scripts/config --enable CONFIG_SMB_SERVER_SMBDIRECT
        ./scripts/config --enable CONFIG_SMB_SERVER_CHECK_CAP_NET_ADMIN
        ./scripts/config --enable CONFIG_SMB_SERVER_KERBEROS5

        make olddefconfig

        make -j$((`nproc`+1)) -C /lib/modules/$(uname -r)/build M=$(pwd)/fs/smb/server modules
        make -j$((`nproc`+1)) -C /lib/modules/$(uname -r)/build M=$(pwd)/fs/smb/client modules

        sudo modprobe cifs
        sudo modprobe ksmbd

        sudo rmmod ksmbd || true
        sudo rmmod cifs || true

        sudo insmod fs/smb/client/cifs.ko
        sudo insmod fs/smb/server/ksmbd.ko

    - name: Compile and install ksmbd-tools
      working-directory: ksmbd-tools
      run: |
        ./autogen.sh
        CC=clang ./configure --enable-asan --sysconfdir=/etc --with-rundir=/run
        make -j$((`nproc`+1))
        sudo make install

    - name: Prepare testsuite
      run: |
        sudo mkdir -p /etc/ksmbd/
        sudo mkdir -p /mnt/1
        sudo mkdir -p /mnt/2
        sudo mkdir -m 777 -p /mnt/test1
        sudo mkdir -m 777 -p /mnt/test2
        sudo mkdir -m 777 -p /mnt/test3

        ksmbd.adduser -P ./ksmbdpwd.db -a testuser -p 1234

        cp cifsd-test-result/testsuites/smb.conf .
        cat smb.conf
        sudo ksmbd.mountd -n -C ./smb.conf -P ./ksmbdpwd.db 2>&1 | tee ksmbd-tools-asan.log &

        sleep 1
        ps -ax | grep smbd
        
    - name: Run xfstests
      working-directory: xfsprogs-dev
      run: |
        make -j$((`nproc`+1)) > /dev/null

        set +e

        sudo ./check cifs/001
        sudo ./check generic/001 generic/002 generic/005 generic/006 generic/007 generic/008 generic/010

        sed -e "s/count=1000/count=100/" -e "s/-p 5/-p 3/" tests/generic/011 > tests/generic/011.new
        sed -e "s/-p 5/-p 3/" tests/generic/011.out > tests/generic/011.out.new
        mv tests/generic/011.new tests/generic/011
        mv tests/generic/011.out.new tests/generic/011.out

        sudo ./check generic/011 generic/013 generic/014 generic/023 generic/024 generic/028 generic/029 generic/030 \
                     generic/032 generic/033 generic/036 generic/037 generic/043 generic/044 generic/045 generic/046 \
                     generic/051 generic/069 generic/070 generic/071 generic/072 generic/074 generic/080 generic/084 \
                     generic/086 generic/091 generic/095 generic/098 generic/095 generic/098 generic/100 generic/103 \
                     generic/109 generic/113 generic/117 generic/124 generic/125 generic/129 generic/130 generic/132 \
                     generic/133 generic/135 generic/141 generic/169 generic/198 generic/207 generic/208 generic/210 \
                     generic/211 generic/212 generic/214 generic/215 generic/221 generic/225 generic/228 generic/236 \
                     generic/239 generic/241 generic/245 generic/246 generic/247 generic/248 generic/249 generic/257 \
                     generic/258 generic/263 generic/308 generic/309 generic/310 generic/313 generic/315 generic/316 \
                     generic/323 generic/337 generic/339 generic/340 generic/344 generic/345 generic/346 generic/349 \
                     generic/350 generic/354 generic/360 generic/377 generic/391 generic/393 generic/394 generic/406 \
                     generic/412 generic/420 generic/428 generic/430 generic/431 generic/432 generic/433 generic/436 \
                     generic/437 generic/438 generic/439 generic/443 generic/445 generic/446 generic/448 generic/451 \
                     generic/452 generic/454 generic/460 generic/461 generic/464 generic/465 generic/469 generic/504 \
                     generic/523 generic/524 generic/528 generic/532 generic/533 generic/539 generic/565 generic/567 \
                     generic/568 generic/599

        set -e

    - name: Run smbtorture
      working-directory: samba
      run: |
        ./configure --disable-cups --disable-iprint --without-ad-dc --without-ads --without-ldap --without-pam --with-shared-modules='!vfs_snapper' > /dev/null
        make -j$((`nproc`+1)) bin/smbtorture > /dev/null

        set +e

        # smb2 connect test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.connect
        sudo rm -rf /mnt/test3/*

        # smb2 read test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.read.eof
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.read.position
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.read.dir
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.read.access
        sudo rm -rf /mnt/test3/*

        # smb2 scan test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.scan.scan
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.scan.getinfo
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.scan.setinfo
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.scan.find
        sudo rm -rf /mnt/test3/*

        # smb2 dir test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.dir.find
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.dir.fixed
        sudo rm -rf /mnt/test3/*
        ##./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.dir.one
        ##sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.dir.many
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.dir.modify
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.dir.sorted
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.dir.file-index
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.dir.large-files
        sudo rm -rf /mnt/test3/*

        # smb2 rename test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.rename.simple
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.rename.simple_nodelete
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.rename.no_sharing
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.rename.share_delete_and_delete_access
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.rename.no_share_delete_but_delete_access
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.rename.share_delete_no_delete_access
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.rename.msword
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.rename.rename_dir_openfile
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.rename.rename_dir_bench
        sudo rm -rf /mnt/test3/*

        # smb2 maxfid test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.maxfid
        sudo rm -rf /mnt/test3/*

        # smb2 sharemode test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.sharemode.sharemode-access
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.sharemode.access-sharemode
        sudo rm -rf /mnt/test3/*

        # smb2 compound test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.compound.related1
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.compound.related2
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.compound.related3
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.compound.unrelated1
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.compound.invalid1
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.compound.invalid2
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.compound.invalid3
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.compound.interim1 #fail
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.compound.interim2
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.compound.compound-break
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.compound.compound-padding
        sudo rm -rf /mnt/test3/*

        # smb2 streams test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.streams.dir
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.streams.io
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.streams.sharemodes
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.streams.names
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.streams.names2
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.streams.names3
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.streams.rename
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.streams.rename2
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.streams.create-disposition
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.streams.attributes
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.streams.delete
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.streams.zero-byte
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.streams.basefile-rename-with-open-stream
        sudo rm -rf /mnt/test3/*

        # smb2 create test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.create.gentest
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.create.blob
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.create.open
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.create.brlocked
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.create.multi
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.create.delete
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.create.leading-slash
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.create.impersonation
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.create.dir-alloc-size
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.create.aclfile
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.create.acldir
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.create.nulldacl
        sudo rm -rf /mnt/test3/*

        # smb2 delete-on-close test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.delete-on-close-perms.OVERWRITE_IF
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 "smb2.delete-on-close-perms.OVERWRITE_IF Existing"
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.delete-on-close-perms.CREATE
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 "smb2.delete-on-close-perms.CREATE Existing"
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.delete-on-close-perms.CREATE_IF
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 "smb2.delete-on-close-perms.CREATE_IF Existing"
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.delete-on-close-perms.FIND_and_set_DOC
        sudo rm -rf /mnt/test3/*

        # smb2 oplock test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.exclusive1
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.exclusive2
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.exclusive3
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.exclusive4
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.exclusive5
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.exclusive6
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.exclusive9
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch1
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch2
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch3
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch4
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch5
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch6
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch7
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch8
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch9
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch9a
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch10
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch11
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch12
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch13
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch14
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch15
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch16
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch19
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch20
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch21
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch22a
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch23
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch24
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch25
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.batch26 #fail
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.stream1 #fail
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.doc
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.brl1
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.brl2
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.brl3
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.levelii500
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.levelii501
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.oplock.levelii502
        sudo rm -rf /mnt/test3/*

        # smb2 session test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.session.reconnect1
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.session.reconnect2
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.session.reauth1
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.session.reauth2
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.session.reauth3
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.session.reauth4

        # smb2 lock test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.valid-request
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.rw-shared
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.rw-exclusive
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.auto-unlock
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.async
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.cancel
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.cancel-tdis
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.cancel-logoff
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.zerobytelength
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.zerobyteread
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.unlock
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.multiple-unlock
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.stacking
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.contend
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.context
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lock.truncate

        # smb2 leases test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.request
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.nobreakself
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.statopen
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.statopen2
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.statopen3
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.upgrade
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.upgrade2
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.upgrade3
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.break
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.oplock
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.multibreak
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.breaking1
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.breaking2
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.breaking3
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.breaking4
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.breaking5
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.breaking6
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.lock1
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.complex1
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.timeout
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.unlink
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.v2_request_parent
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.v2_request
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.v2_epoch1
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.v2_epoch2
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.v2_epoch3
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.v2_complex2
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.lease.v2_rename

        # smb2 acls test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.acls.CREATOR
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.acls.GENERIC
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.acls.OWNER
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.acls.INHERITANCE
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.acls.INHERITFLAGS
        sudo rm -rf /mnt/test3/*
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.acls.DYNAMIC

        # smb2 credits test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.credits.session_setup_credits_granted
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.credits.single_req_credits_granted
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.credits.skipped_mid

        # smb2 durable handle test
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.open-oplock
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.open-lease
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.reopen1
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.reopen1a
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.reopen1a-lease
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.reopen2
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.reopen2a
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.reopen2-lease
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.reopen2-lease-v2
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.reopen3
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.reopen4
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.delete_on_close2
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.file-position
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.lease
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.alloc-size
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-open.read-only
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-v2-open.create-blob
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-v2-open.open-oplock
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-v2-open.open-lease
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-v2-open.reopen1
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-v2-open.reopen1a
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-v2-open.reopen1a-lease
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-v2-open.reopen2
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-v2-open.reopen2b
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-v2-open.reopen2c
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-v2-open.reopen2-lease
        ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.durable-v2-open.reopen2-lease-v2

        set -e

    - name: Report ksmbd-tools
      run: |
        sudo chmod 777 ksmbd-tools-asan.log
        cat ksmbd-tools-asan.log

    - name: Report kernel log
      run: |
        sudo dmesg
